import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import CartHydration from "@/components/CartHydration";
import SyncUserAfterAuth from "@/components/SyncUserAfterAuth";
import { auth0 } from "@/lib/auth0";
import { prisma } from "@/lib/prisma";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth0.getSession();
  const userEmail = session?.user?.email ?? null;
  const userPicture = session?.user?.picture ?? null;
  const isAuthenticated = Boolean(session?.user?.sub);

  let isAdmin = false;
  if (session?.user?.sub) {
    const dbUser = await prisma.user.findUnique({
      where: { auth0Id: session.user.sub },
      select: { role: true },
    });
    isAdmin = dbUser?.role === 'ADMIN';
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <CartHydration isAuthenticated={isAuthenticated} />
        <SyncUserAfterAuth isAuthenticated={isAuthenticated} />
        <Header userEmail={userEmail} userPicture={userPicture} isAdmin={isAdmin} />
        <main className="flex-1">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}